# Generated by Django 2.0.7 on 2018-07-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Usuario Anonimo', max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('telefono', models.IntegerField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(blank=True, upload_to='profileImages/')),
            ],
        ),
    ]
